version: "3"

services:
  vite:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME}_PROJECT"
    restart: unless-stopped
    ports:
      - "8080:8080"
    command:
      sh -c "cd app && npm run serve:node"



#  nginx:
#    image: nginx:1.13
#    container_name: "${COMPOSE_PROJECT_NAME}_NGINX"
#    ports:
#      - "4115:80"
#    volumes:
#      - ./:/var/www
#      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
#    depends_on:
#      - vite
